- name: copy grafana agent config file
  template:
    src: files/grafana-agent.yaml.j2
    dest: /etc/grafana-agent.yaml

- name: install gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: add gpg key
  apt_key:
    url: "https://apt.grafana.com/gpg.key"
    validate_certs: no

- name: add repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"             
    state: present
    validate_certs: no

- name: install grafana-agent
  apt:
    name: grafana-agent
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Start service grafana-agent
  systemd:
    name: grafana-agent
    state: started
    enabled: yes

- name: Enable service grafana-agent
  systemd:
    name: grafana-agent.service
    enabled: true
    masked: no